# Generated by Django 3.1.3 on 2020-12-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20201224_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
