# Generated by Django 3.1.3 on 2020-12-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_comment_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('n', 'No Color'), ('red', 'Red'), ('white', 'White'), ('black', 'Black')], max_length=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('n', 'No Size'), ('s', 'S'), ('m', 'M'), ('l', 'L')], max_length=5),
        ),
    ]
