# Generated by Django 3.1.3 on 2020-12-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20201225_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='count',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
